[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "gravity-toolkit"
version = "1.2.7"
description = "Python tools for working with time-variable gravity fields"
keywords = [
    "GRACE",
    "GRACE-FO",
    "Gravity",
    "satellite geodesy",
    "spherical harmonics",
]

authors = [
    {name = "Tyler Sutterley"},
    {email = "tsutterl@uw.edu"}
]
maintainers = [
    { name = "gravity-toolkit contributors" }
]
license = "MIT"
license-files = ["LICENSE"]
readme = {file = "README.md", content-type = "text/markdown"}

requires-python = "~=3.6"
dependencies = [
    "boto3",
    "future",
    "lxml",
    "matplotlib",
    "netCDF4",
    "numpy",
    "platformdirs",
    "python-dateutil",
    "pyyaml",
    "scipy>=1.10.1",
]

classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Physics",
]

[project.urls]
Homepage = "https://gravity-toolkit.readthedocs.io"
Documentation = "https://gravity-toolkit.readthedocs.io"
Repository = "https://github.com/tsutterley/gravity-toolkit"
Issues = "https://github.com/tsutterley/gravity-toolkit/issues"

[project.optional-dependencies]
doc = ["docutils", "graphviz", "myst-nb", "numpydoc", "sphinx", "sphinx-argparse>=0.4", "sphinxcontrib-bibtex", "sphinx-design", "sphinx_rtd_theme"]
all = ["geoid-toolkit", "h5py", "jupyterlab", "jupyterlab_widgets", "notebook"]
aws = ["dask", "obstore", "pyarrow", "s3fs", "zarr>=3"]
dev = ["flake8", "pytest>=4.6", "pytest-cov", "pytest-xdist"]
map = ["cartopy", "gdal", "pyshp", "shapely"]

[project.scripts]
# Data Access (datasets)
"cnes_grace_sync.py" = "gravity_toolkit.datasets.cnes_grace_sync:main"
"esa_costg_swarm_sync.py" = "gravity_toolkit.datasets.esa_costg_swarm_sync:main"
"gfz_icgem_costg_ftp.py" = "gravity_toolkit.datasets.gfz_icgem_costg_ftp:main"
"gfz_isdc_dealiasing_sync.py" = "gravity_toolkit.datasets.gfz_isdc_dealiasing_sync:main"
"gfz_isdc_grace_sync.py" = "gravity_toolkit.datasets.gfz_isdc_grace_sync:main"
"itsg_graz_grace_sync.py" = "gravity_toolkit.datasets.itsg_graz_grace_sync:main"
"podaac_cumulus.py" = "gravity_toolkit.datasets.podaac_cumulus:main"
# Dealiasing (dealiasing)
"aod1b_geocenter.py" = "gravity_toolkit.scripts.aod1b_geocenter:main"
"aod1b_oblateness.py" = "gravity_toolkit.scripts.aod1b_oblateness:main"
"dealiasing_global_uplift.py" = "gravity_toolkit.scripts.dealiasing_global_uplift:main"
"dealiasing_monthly_mean.py" = "gravity_toolkit.scripts.dealiasing_monthly_mean:main"
# Degree-1 (geocenter)
"calc_degree_one.py" = "gravity_toolkit.scripts.calc_degree_one:main"
"geocenter_compare_tellus.py" = "gravity_toolkit.scripts.geocenter_compare_tellus:main"
"geocenter_monte_carlo.py" = "gravity_toolkit.scripts.geocenter_monte_carlo:main"
"geocenter_ocean_models.py" = "gravity_toolkit.scripts.geocenter_ocean_models:main"
"geocenter_processing_centers.py" = "gravity_toolkit.scripts.geocenter_processing_centers:main"
"monte_carlo_degree_one.py" = "gravity_toolkit.scripts.monte_carlo_degree_one:main"
# Geographic Plot Tools (mapping)
"plot_AIS_grid_3maps.py" = "gravity_toolkit.mapping.plot_AIS_grid_3maps:main"
"plot_AIS_grid_4maps.py" = "gravity_toolkit.mapping.plot_AIS_grid_4maps:main"
"plot_AIS_grid_maps.py" = "gravity_toolkit.mapping.plot_AIS_grid_maps:main"
"plot_AIS_grid_movie.py" = "gravity_toolkit.mapping.plot_AIS_grid_movie:main"
"plot_AIS_GrIS_maps.py" = "gravity_toolkit.mapping.plot_AIS_GrIS_maps:main"
"plot_AIS_regional_maps.py" = "gravity_toolkit.mapping.plot_AIS_regional_maps:main"
"plot_AIS_regional_movie.py" = "gravity_toolkit.mapping.plot_AIS_regional_movie:main"
"plot_global_grid_3maps.py" = "gravity_toolkit.mapping.plot_global_grid_3maps:main"
"plot_global_grid_4maps.py" = "gravity_toolkit.mapping.plot_global_grid_4maps:main"
"plot_global_grid_5maps.py" = "gravity_toolkit.mapping.plot_global_grid_5maps:main"
"plot_global_grid_9maps.py" = "gravity_toolkit.mapping.plot_global_grid_9maps:main"
"plot_global_grid_maps.py" = "gravity_toolkit.mapping.plot_global_grid_maps:main"
"plot_global_grid_movie.py" = "gravity_toolkit.mapping.plot_global_grid_movie:main"
"plot_GrIS_grid_3maps.py" = "gravity_toolkit.mapping.plot_GrIS_grid_3maps:main"
"plot_GrIS_grid_5maps.py" = "gravity_toolkit.mapping.plot_GrIS_grid_5maps:main"
"plot_GrIS_grid_maps.py" = "gravity_toolkit.mapping.plot_GrIS_grid_maps:main"
"plot_GrIS_grid_movie.py" = "gravity_toolkit.mapping.plot_GrIS_grid_movie:main"
"plot_QML_grid_3maps.py" = "gravity_toolkit.mapping.plot_QML_grid_3maps:main"
# Use Cases / Processing (scripts)
"calc_harmonic_resolution.py" = "gravity_toolkit.scripts.calc_harmonic_resolution:main"
"calc_mascon.py" = "gravity_toolkit.scripts.calc_mascon:main"
"calc_sensitivity_kernel.py" = "gravity_toolkit.scripts.calc_sensitivity_kernel:main"
"combine_harmonics.py" = "gravity_toolkit.scripts.combine_harmonics:main"
"convert_harmonics.py" = "gravity_toolkit.scripts.convert_harmonics:main"
"grace_mean_harmonics.py" = "gravity_toolkit.scripts.grace_mean_harmonics:main"
"grace_raster_grids.py" = "gravity_toolkit.scripts.grace_raster_grids:main"
"grace_spatial_error.py" = "gravity_toolkit.scripts.grace_spatial_error:main"
"grace_spatial_maps.py" = "gravity_toolkit.scripts.grace_spatial_maps:main"
"make_grace_index.py" = "gravity_toolkit.scripts.make_grace_index:main"
"mascon_reconstruct.py" = "gravity_toolkit.scripts.mascon_reconstruct:main"
"piecewise_grace_maps.py" = "gravity_toolkit.scripts.piecewise_grace_maps:main"
"quick_mascon_plot.py" = "gravity_toolkit.scripts.quick_mascon_plot:main"
"quick_mascon_regress.py" = "gravity_toolkit.scripts.quick_mascon_regress:main"
"regress_grace_maps.py" = "gravity_toolkit.scripts.regress_grace_maps:main"
"run_grace_date.py" = "gravity_toolkit.scripts.run_grace_date:main"
"run_sea_level_equation.py" = "gravity_toolkit.scripts.run_sea_level_equation:main"
"scale_grace_maps.py" = "gravity_toolkit.scripts.scale_grace_maps:main"
# production code
"calc_SLR_RMS.py" = "gravity_toolkit.scripts.calc_SLR_RMS:main"
"combine_HEX_ATM_errors.py" = "gravity_toolkit.scripts.combine_HEX_ATM_errors:main"
"combine_HEX_Caron_errors.py" = "gravity_toolkit.scripts.combine_HEX_Caron_errors:main"
"combine_HEX_leakage.py" = "gravity_toolkit.scripts.combine_HEX_leakage:main"
"combine_HEX_mascons.py" = "gravity_toolkit.scripts.combine_HEX_mascons:main"
"combine_HEX_mascon_timeseries.py" = "gravity_toolkit.scripts.combine_HEX_mascon_timeseries:main"
"combine_HEX_OBP_errors.py" = "gravity_toolkit.scripts.combine_HEX_OBP_errors:main"
"combine_HEX_SLF_errors.py" = "gravity_toolkit.scripts.combine_HEX_SLF_errors:main"
"combine_HEX_spherical_caps.py" = "gravity_toolkit.scripts.combine_HEX_spherical_caps:main"
"combine_HEX_TWC_errors.py" = "gravity_toolkit.scripts.combine_HEX_TWC_errors:main"
"combine_sea_level_data.py" = "gravity_toolkit.scripts.combine_sea_level_data:main"
"copy_parameter_files.py" = "gravity_toolkit.scripts.copy_parameter_files.py:main"
"create_public_SLF_data.py" = "gravity_toolkit.scripts.create_public_SLF_data:main"
"create_public_timeseries.py" = "gravity_toolkit.scripts.create_public_timeseries:main"
"delta_degree_one.py" = "gravity_toolkit.scripts.delta_degree_one:main"
"geocenter_spatial_maps.py" = "gravity_toolkit.scripts.geocenter_spatial_maps:main"
"gia_covariance_errors_caron.py" = "gravity_toolkit.scripts.gia_covariance_errors_caron:main"
"grace_spatial_differences.py" = "gravity_toolkit.scripts.grace_spatial_differences:main"
"grace_spatial_mask.py" = "gravity_toolkit.scripts.grace_spatial_mask:main"
"grace_spatial_mean.py" = "gravity_toolkit.scripts.grace_spatial_mean:main"
"kernel_degree_one_error.py" = "gravity_toolkit.scripts.kernel_degree_one_error:main"
"kernel_degree_one.py" = "gravity_toolkit.scripts.kernel_degree_one:main"
"make_sea_level_error_shells.py" = "gravity_toolkit.scripts.make_sea_level_error_shells:main"
"make_sea_level_mascon_shells.py" = "gravity_toolkit.scripts.make_sea_level_mascon_shells:main"
"make_sea_level_shells.py" = "gravity_toolkit.scripts.make_sea_level_shells:main"
"model_degree_one.py" = "gravity_toolkit.scripts.model_degree_one:main"
"nominal_grace_date.py" = "gravity_toolkit.scripts.nominal_grace_date:main"
"plot_mascon_SLF_combined.py" = "gravity_toolkit.scripts.plot_mascon_SLF_combined:main"
"plot_mascon_SLF_iterations.py" = "gravity_toolkit.scripts.plot_mascon_SLF_iterations:main"
"plot_mascon_SLF_timeseries.py" = "gravity_toolkit.scripts.plot_mascon_SLF_timeseries:main"
"plot_SLR_azimuthal.py" = "gravity_toolkit.scripts.plot_SLR_azimuthal:main"
"plot_SLR_zonals.py" = "gravity_toolkit.scripts.plot_SLR_zonals:main"
"regional_spherical_caps.py" = "gravity_toolkit.scripts.regional_spherical_caps:main"
"remove_grace_spatial.py" = "gravity_toolkit.scripts.remove_grace_spatial:main"
"remove_mascon_reconstruct.py" = "gravity_toolkit.scripts.remove_mascon_reconstruct:main"
"remove_sea_level_errors.py" = "gravity_toolkit.scripts.remove_sea_level_errors:main"
"remove_sea_level_fields.py" = "gravity_toolkit.scripts.remove_sea_level_fields:main"
"sea_level_differences.py" = "gravity_toolkit.scripts.sea_level_differences:main"
"sea_level_error.py" = "gravity_toolkit.scripts.sea_level_error:main"
"sea_level_mean.py" = "gravity_toolkit.scripts.sea_level_mean:main"
"sea_level_regress.py" = "gravity_toolkit.scripts.sea_level_regress:main"
"sea_level_stokes.py" = "gravity_toolkit.scripts.sea_level_stokes:main"
"simple_parallel_shell.py" = "gravity_toolkit.scripts.simple_parallel_shell:main"
"upload_to_figshare.py" = "gravity_toolkit.scripts.upload_to_figshare:main"

[tool.setuptools.packages.find]
exclude = ["test*", "run*"]

[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = ".git"
addopts = "-n auto --verbose --capture=no -W ignore::UserWarning"
python_files = [
    "test*.py"
]
testpaths = [
    "test"
]

[tool.coverage.run]
branch = true
source = [
    "gravity-toolkit",
]
omit = [
    "setup.py",
    "access/*",
    "dealiasing/*",
    "doc/*",
    "geocenter/*",
    "mapping/*",
    "scripts/*",
    "test/*",
    "utilities/*",
]

[tool.coverage.report]
show_missing = true
precision = 2

[tool.ruff]
line-length = 80
indent-width = 4
exclude = [
    ".git",
    ".pixi",
    "build",
    "run",
    "test",
]

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # ruff-specific
    "RUF",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false

[tool.pixi.workspace]
name = "gravity-toolkit"
authors = ["gravity-toolkit contributors"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tool.pixi.pypi-dependencies]
gravity-toolkit = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
all = { features = ["all"], solve-group = "default" }
aws = { features = ["all", "aws"], solve-group = "default" }
dev = { features = ["all", "dev", "map", "doc"], solve-group = "default" }
doc = { features = ["all", "doc"], solve-group = "default" }
map = { features = ["all", "map"], solve-group = "default" }

[tool.pixi.tasks.start]
cmd = "jupyter lab"
cwd = "doc/source/notebooks"
description = "Start JupyterLab in the notebooks directory"

[tool.pixi.tasks.export-env]
args = [ { "arg" = "flags", "default" = "" } ]
cmd = "pixi workspace export conda-environment {{ flags }} > environment.yml"
description = "Export workspace to a conda environment file" 

[tool.pixi.feature.doc.tasks.docs]
args = [ { "arg" = "builder", "default" = "html"}, { "arg" = "flags", "default" = "" } ]
cmd = "make {{ builder }} {{ flags }}"
cwd = "doc"
description = "Create documentation with sphinx"

[tool.pixi.feature.doc.tasks.clean-docs]
args = [ { "arg" = "builder", "default" = "html"}, { "arg" = "flags", "default" = "" } ]
cmd = "make clean && make {{ builder }} {{ flags }}"
cwd = "doc"
description = "Remove build artifacts and rebuild the documentation with sphinx"

[tool.pixi.feature.dev.tasks.test]
args = [ { "arg" = "flags", "default" = "" }, { "arg" = "test", "default" = "." } ]
cmd = "pytest {{ flags }} {{ test }}"
cwd = "test"
description = "Run the pytest suite"

[tool.pixi.feature.dev.tasks.coverage]
args = [ { "arg" = "flags", "default" = "" } ]
cmd = "pytest -n=0 --cov=gravity_toolkit --junitxml=pytest.xml --cov-report=xml {{ flags }} test"
description = "Run the pytest suite and create coverage reports"

[tool.pixi.feature.dev.tasks.lint]
args = [ { "arg" = "flags", "default" = "--select=E9,F63,F7,F82 --show-source" }, { "arg" = "test", "default" = "." } ]
cmd = "flake8 {{ test }} --count {{ flags }} --statistics --extend-exclude 'build/,run/,*.ipynb_checkpoints/,.pixi/'"
description = "Run flake8 to check for compilation errors"

[tool.pixi.dependencies]
boto3 = "*"
future = "*"
lxml = "*"
matplotlib-base = "*"
netcdf4 = "*"
numpy = "*"
platformdirs = "*"
python-dateutil = "*"
pyyaml = "*"
scipy = "*"

[tool.pixi.feature.all.dependencies]
geoid-toolkit = "*"
h5py = "*"
ipympl = "*"
ipywidgets = "*"
jupyterlab = "*"
jupyterlab_widgets = "*"
notebook = "*"

[tool.pixi.feature.aws.dependencies]
dask = "*"
obstore = "*"
pyarrow = "*"
s3fs = "*"
zarr = ">=3"

[tool.pixi.feature.dev.dependencies]
flake8 = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"

[tool.pixi.feature.doc.dependencies]
docutils = "*"
graphviz = "*"
markupsafe = "*"
myst-nb = "*"
numpydoc = "*"
sphinx = "*"
sphinx-argparse = "*"
sphinxcontrib-bibtex = "*"
sphinx-design = "*"
sphinx_rtd_theme = "*"

[tool.pixi.feature.map.dependencies]
cartopy = "*"
gdal = "*"
pyshp = "*"
shapely = "*"
